scrapers:
  crypto_google_trend:
    data_dir: data/crypto_google_trend/
    historical_data_filename: historical_data.csv
    new_data_filename: new_data.csv
    indicator_data_filename: indicator.csv
    pine_script_path: pinescript.txt
    features: ['btc', 'eth', 'doge']
  btc_vix_ratio:
    data_dir: data/btc_vix_ratio/
    historical_data_filename: historical_data.csv
    new_data_filename: new_data.csv
    indicator_data_filename: indicator.csv
    pine_script_path: pinescript.txt
    features: [btc_vix]
  crypto_youtuber_view:
    data_dir: data/crypto_youtuber_view/
    historical_data_filename: historical_data.csv
    new_data_filename: new_data.csv
    indicator_data_filename: indicator.csv
    pine_script_path: pinescript.txt
    features: ['btc', 'eth', 'doge']
log_path: ''