[project]
name = "tradingview-external-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas>=2.2.3",
    "pytrends>=4.9.2",
    "yfinance>=0.2.55",
]
